export const my_tickets = [
  {
    id: '1',
    eventTitle: 'Coldplay World Tour 2025',
    date: '2025-06-15',
    time: '19:30',
    venue: 'Wembley Stadium, London',
    ticketType: 'VIP',
    quantity: 2,
    qrCodeUrl: require('../assets/qrcode_chatgpt.com.png'),
    status: 'Active',
  },
  {
    id: '2',
    eventTitle: 'Tech Expo 2025',
    date: '2025-07-20',
    time: '10:00',
    venue: 'Silicon Valley Convention Center',
    ticketType: 'General Admission',
    quantity: 1,
    qrCodeUrl: require('../assets/qrcode_chatgpt.com.png'),
    status: 'Active',
  },
  {
    id: '3',
    eventTitle: 'Stand-Up Night with Kevin Hart',
    date: '2025-05-05',
    time: '21:00',
    venue: 'Madison Square Garden, NY',
    ticketType: 'Premium',
    quantity: 2,
    qrCodeUrl: require('../assets/qrcode_chatgpt.com.png'),
    status: 'Used',
  },
  {
    id: '4',
    eventTitle: 'Movie Premiere: The AI Era',
    date: '2025-04-28',
    time: '18:00',
    venue: 'Downtown Cinema, LA',
    ticketType: 'Standard',
    quantity: 3,
    qrCodeUrl: require('../assets/qrcode_chatgpt.com.png'),
    status: 'Cancelled',
  },
];
